CREATE PROCEDURE [dbo].[usp_Cumplimiento_Add]
@UidTarea uniqueidentifier,
@UidDepartamento uniqueidentifier = null,
@UidArea uniqueidentifier = null,
@UidUsuario uniqueidentifier,
@DtFechaHora datetime = null,
@DtFechaProgramada date,
@UidEstadoCumplimiento uniqueidentifier,
@VchObservacion nvarchar(200) = null,
@UrlFoto nvarchar(50) = null,
@BitValor bit = null,
@DcValor1 decimal(18, 4) = null,
@DcValor2 decimal(18, 4) = null,
@UidOpcion uniqueidentifier = null,
@UidTurno uniqueidentifier = null
AS

SET NOCOUNT ON

INSERT INTO Cumplimiento (UidCumplimiento,
						  UidTarea,
						  UidDepartamento,
						  UidArea,
						  UidUsuario,
						  DtFechaHora,
						  DtFechaProgramada,
						  UidEstadoCumplimiento,
						  VchObservacion, 
						  UrlFoto,
						  BitValor,
						  DcValor1,
						  DcValor2,
						  UidOpcion,
						  UidTurno)
				  VALUES (NEWID(),
						  @UidTarea,
						  @UidDepartamento,
						  @UidArea,
						  @UidUsuario,
						  @DtFechaHora,
						  @DtFechaProgramada,
						  @UidEstadoCumplimiento,
						  @VchObservacion,
						  @UrlFoto,
						  @BitValor,
						  @DcValor1,
						  @DcValor2,
						  @UidOpcion,
						  @UidTurno)