#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CodorniX.AndroidApp.Resource", IsApplication=true)]

namespace CodorniX.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int assignment_return1600 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Logout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tasks = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int bienvenido = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int btnAsignaciones = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnLogout = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int btnTarea = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int button1 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int descripcion = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int error = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int login = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int password = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int tarea = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int textView1 = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int tvDepartamento = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int tvTarea = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int tvTurno = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int username = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Asignaciones = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_asignacion = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_tarea = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TareaInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Tareas = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int errorPassword = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int errorSucursal = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int errorUsername = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int password = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int preference_key_name = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int username = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
