CREATE TABLE [dbo].[URL] (
    [UidUrl] UNIQUEIDENTIFIER CONSTRAINT [DF_URL_UidUrl] DEFAULT (newid()) NOT NULL,
    [VchUrl] NVARCHAR (50)    NULL,
    CONSTRAINT [PK_URL] PRIMARY KEY CLUSTERED ([UidUrl] ASC)
);

